### ISSUE TITLE
ILV Date filter, acting strange

### ISSUE THREAD

**Issue by MarcelK66** [ILoveHubGit/ILV#1]
When I select the date as shown in the interface on the screen, there is no data shown ( see attachments ILV01 and ILV02)
Selected 2023-03-15 12:55:07 ( which is the date of the interface ), I expected both to appear

The dates of the interface in the link and interface self are the same, when I inspect the swaggerUI. ( see json attachments )

When I raise the seconds, or minutes this makes no difference, until I raise the hours then all become visible. ( see attachment ILV03 )

For now I don't see why this is happening ...

Marcel

[response_1679481456269.json.txt](https://github.com/ILoveHubGit/ILV/files/11039237/response_1679481456269.json.txt)
[response_1679481456300.json.txt](https://github.com/ILoveHubGit/ILV/files/11039238/response_1679481456300.json.txt)
![ILV03](https://user-images.githubusercontent.com/118895421/226884189-e5ea83ca-b072-401a-bd6c-27dc6443ae51.JPG)
![ILV02](https://user-images.githubusercontent.com/118895421/226884190-7dcb5e0b-4544-4c14-afc9-69ea0388c370.JPG)
![ILV01](https://user-images.githubusercontent.com/118895421/226884191-066e3a9d-cb1e-43c8-b72f-ccf7ce79427f.JPG)

**Comment by ILoveHubGit** [comment]
Thanks for issuing this bug.
This happens because the DeplymentDate of the Interface is shown while filtering of the Links is done based on the DeploymentDate of the Link. This last one is not shown and that causes the confusion.

I'll change the layout and will show the DeploymentDate of the Link instead of the one of the Interface
